### ISSUE TITLE
How to logout using submit?

### ISSUE THREAD

**Issue by meysammahfouzi** [oc-shopaholic/oc-buddies-plugin#31]
I don't understand how to logout using submit. I've added to following to the top of the page:

```
[Logout]
mode = "submit"
redirect_on = 1
redirect_page = "index"
==
```

Now, what should I do in the `onclick` of the logout button?

**Comment by kharanenka** [comment]
Hi! You can create fake page with URL = '/logout' and attach Logout component to it.
Logout button is link on logout page.
User clicking on link will get redirect to index page after logout

**Comment by meysammahfouzi** [comment]
Alright, thanks. I think it needs to be documented :)

**Comment by kharanenka** [comment]
Thanks you for your question. I will add to documentation
