### ISSUE TITLE
Bug with vkontakte authorization

### ISSUE THREAD

**Issue by definer** [oc-shopaholic/oc-buddies-plugin#34]
Hi, I see a bug when logging in to VKontakte

When logging in to VKontakte, Buddies does not see the received email and assigns a fake email

**Comment by kharanenka** [comment]
Hi! For VK, email does not always return from API.

**Comment by definer** [comment]
Certainly, but on my project an email address is open, and the mailing address is sent to the accessTokenResponseBody object, but not to the email field

**Comment by kharanenka** [comment]
You can debug plugins/lovata/buddies/components/SocialiteLogin.php component, login(), findUserByEmail() methods.
We get email from Socialite packeage. 
You can debug socialite user object in line:
```php
//line 96
$obUserData = \Laravel\Socialite\Facades\Socialite::driver($sDriverCode)->user();
```

You can check user email in line:
```php
//line 158
$sEmail = $obUserData->getEmail();
```
