### ISSUE TITLE
[Enhancement] Add login / logout events

### ISSUE THREAD

**Issue by kordima** [oc-shopaholic/oc-buddies-plugin#35]
I need to do something after the user login / logout (e.g. clear Cart-> user_data).
I suggest adding events: lovata.buddies.login and lovata.buddies.logout.

**Comment by kharanenka** [comment]
Hi! It is good idea. Do you can contribution this events?

**Comment by kordima** [comment]
Added and tested:

[AuthHelperManager.zip](https://github.com/oc-shopaholic/oc-buddies-plugin/files/3498480/AuthHelperManager.zip)

**Comment by lautsevich** [comment]
@kordima, could you please open a Pull Request with this code addition?

**Comment by kordima** [comment]
Sample code for clear Shopaholic Cart->user_data after login/logout
```
        Event::listen('lovata.buddies.*', function($user) {
            if (ends_with(Event::firing(), '.login') || ends_with(Event::firing(), '.logout')) {
                Log::debug(Event::firing());
                $obCart = CartProcessor::instance()->getCartObject();
                if (!empty($obCart)) {
                    $obCart->user_data = null;
                    $obCart->save();
                }
            }
        });
```

**Comment by kordima** [comment]
[AuthHelperManager.zip](https://github.com/oc-shopaholic/oc-buddies-plugin/files/3553952/AuthHelperManager.zip) v.2
Added:
```
    const EVENT_LOGIN = 'lovata.buddies.login';
    const EVENT_LOGOUT = 'lovata.buddies.logout';
```

**Comment by lautsevich** [comment]
@kordima, great! could you please open a Pull Request with your code addition?

**Comment by kordima** [comment]
@Павел, did.

**Comment by lautsevich** [comment]
We'll close this issue after related PR approvement.
