### ISSUE TITLE
Change User Details

### ISSUE THREAD

**Issue by Cambrai1** [oc-shopaholic/oc-buddies-plugin#37]
Hi there,

is there a way to allow for the front end user to change his details? I have a profile page and I want to give the user the ability to change their details if they want to... is there any way to do this?

**Comment by kordima** [comment]
With this wonderful component you can make any front for user profile. 
You need to do this.
https://octobercms.com/docs/cms/components/

**Comment by lautsevich** [comment]
Hi @Cambrai1, have you checked the docs provided by kordima?

**Comment by kharanenka** [comment]
Hi @Cambrai1 !
You can use UserPage component for saving user details.
