### ISSUE TITLE
UserData on Backend (in own plugin)

### ISSUE THREAD

**Issue by davidprovaznikj** [oc-shopaholic/oc-buddies-plugin#39]
Hello, I have a question.
How I get user data in my own plugin?

On frontend is easy:

```
{% set obUser = UserData.get %}
{{ obUser.email }}
```
On backend, in my own plugin: I don't know what to do

Thanks

**Comment by kharanenka** [comment]
Hi!
```php
use Lovata\Buddies\Facades\AuthHelper;

//Get auth user object
$obUser = AuthHelper::getUser();
```

**Comment by davidprovaznikj** [comment]
> Hi!
> 
> ```
> use Lovata\Buddies\Facades\AuthHelper;
> 
> //Get auth user object
> $obUser = AuthHelper::getUser();
> ```

This part of code is not working in boot() function of my own plugin.
AuthHelper not exist yet if plugin booting.

I tried place your code to registerComponents() function (standard plugin function) -->  this is working, but this is only bad workaround..
Thanks.
