### ISSUE TITLE
Session after registration

### ISSUE THREAD

**Issue by PictureElement** [oc-shopaholic/oc-buddies-plugin#41]
Hi,

Assuming I have some items in the cart.

1. Following a successful login, the items are still in the cart.
2. Following a registration (without automatic authorization, with user activation) and an immediate login, the cart gets empty.
3. Following a registration (with automatic authorization, with user activation), the cart gets empty.

Is there a way to keep the items in the cart for cases 2 and 3?

Thanks.

**Comment by kharanenka** [comment]
Maybe this is a bug. I am not 100% sure. I need to check 2 and 3 cases

**Comment by PictureElement** [comment]
Thanks.
