### ISSUE TITLE
Login with 'Remember me' checked

### ISSUE THREAD

**Issue by mennax** [oc-shopaholic/oc-buddies-plugin#44]
return this error:

openssl_encrypt() expects parameter 1 to be string, array given
/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php line 91

system build 464
Buddies 1.8.0

**Comment by kharanenka** [comment]
Hi! Please check if bug is reproduced in 1.8.1 plugin version.

**Comment by mennax** [comment]
Hi Kharanenka, fixed! Thank's
